### ISSUE TITLE
Min Quitar iconos de los submenús

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#10]
No hay tanta variedad de iconos, y por tanto quedan mal.

![descarga](https://cloud.githubusercontent.com/assets/20475209/18023681/4edb1296-6bfc-11e6-8b2c-78f4c12852f8.png)

![descarga 10](https://cloud.githubusercontent.com/assets/20475209/18024153/0717912a-6c04-11e6-8094-3270bb992211.png)

**Comment by mecheverria** [comment]
Resuelto
