### ISSUE TITLE
Min - Error en la cabecera

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#12]
En la cabecera veo 3 errores:

1- Hay un punto y coma que sobra.
2- Al lado del usuario hay algo que no tiene sentido: (1)
3- El acceso a la TPV se llama POS. Además quedamos en que sería un icono independiente en la misma cabecera. Te pongo el icono de font awesone que creo que encajaría, aunque no es el ideal porque todavía no han lanzado uno adecuado: http://fontawesome.io/icon/credit-card-alt/ 

![descarga 2](https://cloud.githubusercontent.com/assets/20475209/18023786/c71e33b8-6bfd-11e6-8c4e-f3468454fe4c.png)

**Comment by mecheverria** [comment]
Resuelto
