### ISSUE TITLE
Cambiar mensaje de estadísticas sin datos

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#13]
Lo pongo como bug porque así es como lo van a ver nuestros clientes.
Propongo cambiar ese mensaje cutre por simplemente un "Todavía no hay datos" en un color gris claro, una fuente mediana-grande y centrado en el espacio. Estilo marca de agua pero con elegancia.

![descarga 3](https://cloud.githubusercontent.com/assets/20475209/18023843/b99588e4-6bfe-11e6-8766-6318464cdc38.png)

**Comment by mecheverria** [comment]
No he podido reproducir el error
