### ISSUE TITLE
Mi - Errores en las páginas de estadísticas

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#14]
1- No se ve todo el texto cuando hay espacio de sobra.
2- En las estadísticas "Informes de vendedores" esa información está en inglés.
3- En la página 1 pone anterior. Sin que hayan registros pone anterior y siguiente.

![descarga 4](https://cloud.githubusercontent.com/assets/20475209/18023860/2dd45ec4-6bff-11e6-8540-530bddbe174f.png)

**Comment by mecheverria** [comment]
Resuelto
