### ISSUE TITLE
Mi - Error de marca de página en el menú

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#15]
Al entrar en un link del menú, este se queda de un color más oscuro para indicar en que página estamos actualmente. Pues bien, pinchemos en el enlace que pinchemos del menú, el link "panel de control" siempre queda marcado a la vez que el enlace en el que hemos pinchado. 

![descarga 5](https://cloud.githubusercontent.com/assets/20475209/18023925/40f07050-6c00-11e6-913c-257a38c4cfcd.png)

**Comment by mecheverria** [comment]
Resuelto
