### ISSUE TITLE
Mi - Errores en la configuración

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#16]
1- Los botones están montados.
2- Rótulo en inglés y no puedo editar el nombre de la tienda.
3-Sobra la url de la tienda.
4-En inglés.
5-Para redfidelis o catinfog sobra cantidad a no ser que se puedan configurar las geozonas. Simplemente habría que ocultarlo por css y activarlo llegado el caso, me parece a mi.
6-No se ni si funciona. Eso no estaba en tillmagic.
7-Está en inglés.
8-En inglés. En realidad lo que se debe decir es que en qué idioma quieres los productos, no la "webstore".
9-En inglés.
10-En inglés.
11-En inglés.
12-En inglés.
13-En inglés.
14-En inglés y además no hay espacio par ala frase y queda mal.
15-El botón de la x necesita más altura y un color acorde con el panel, por ejemplo rojo.
16-En inglés, y el color del botón debería ser como el resto del panel: o azul o verde (porque añade algo, al contrario del rojo que borra, el azul no quedaría bien porque sería para guardar cambios, creo).
17-En inglés.

![descarga 6](https://cloud.githubusercontent.com/assets/20475209/18024018/9ce4a47a-6c01-11e6-9c4f-447f7ea435f5.png)

![descarga 7](https://cloud.githubusercontent.com/assets/20475209/18024019/a133cfc4-6c01-11e6-8fd3-005e484beb45.png)

![descarga 8](https://cloud.githubusercontent.com/assets/20475209/18024021/a58c5b36-6c01-11e6-80b0-800c554fae52.png)

**Comment by mecheverria** [comment]
Resuelto
