### ISSUE TITLE
Mi - Error en Ofertas

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#18]
1- En todos lados ese botón se llama "guardar" y aquí "salvar cambios".
2-Al entrar en "Central de compra"s > "Ofertas" aparece marcada también la sección de "Central de ventas" > "Ofertas especiales". 
3-Aparece el botón anterior cuando estamos en la página 1. 

![descarga 11](https://cloud.githubusercontent.com/assets/20475209/18024193/e5d412da-6c04-11e6-87db-1a0723397794.png)

**Comment by mecheverria** [comment]
Solucionado
