### ISSUE TITLE
Mi - Hay que mejorar la sección de compras

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#2]
Las opciones de producto no son responsive. 
Hay que mejorar la distribución de la ficha del producto en el movil. Añadir al carrito está al final. Al igual que las opciones de producto.
Los botones "Catálogo" "Carrito" "Producto" "Condiciones" tienen que desaparecer. Es más útil un camino de migas y poner el carrito arriba en la barra del menú principal.

**Comment by mecheverria** [comment]
Resuelto
