### ISSUE TITLE
Mi - enlaces de ayuda son erroneos

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#20]
No van los enlaces de ayuda en la tpv. Los enlaces correctos son estos:

Manual --> http://tillmagic.com/manual/
Support ticket cambiar por Support --> http://tillmagic.com/contact-support/
FAQ --> http://tillmagic.com/faq/
Latests Updates --> http://tillmagic.com/tag/release/
Our web elinminar.

![descarga 1](https://cloud.githubusercontent.com/assets/20475209/18123886/3051a372-6f70-11e6-99b6-f373d83b0ef1.png)

**Comment by mecheverria** [comment]
Hecho
