### ISSUE TITLE
Mi - Error en las ofertas?

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#21]
He detectado dos posibles errores en la sección Nuestras ofertas:

1-¿En catinfog debería existir esta sección?
2-¿Dos ofertas para un mismo producto?

![descarga 2](https://cloud.githubusercontent.com/assets/20475209/18124065/f56abb12-6f70-11e6-88d0-f2ffbe7b8ac3.png)

**Comment by mecheverria** [comment]
Puede haber dos ofertas del mismo producto, si tienen distinta fecha.
