### ISSUE TITLE
Mi - Error gordo en Opciones

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#22]
En primer lugar, no has arreglado lo botones montados.
En segundo lugar, el error que me ha salido es gordo. Cada vez que pulso en guardar me ha salta el error de la primera imagen.

Puedes probar el panel en catinfog.com/demo/tpv/admin_pos

![descarga 3](https://cloud.githubusercontent.com/assets/20475209/18124243/b83ba20a-6f71-11e6-9650-caa82f7a4a8f.png)

**Comment by mecheverria** [comment]
solucionado
