### ISSUE TITLE
Mi - Error en la factura

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#23]
He visto varios errores en la factura que aparece en "historial de ventas".
1-Un error.
2-El comentario sobra a no ser que pueda ser editado.
3-El botón "enviar por correo" no funciona. O esa es la impresión que da porque no aparece ningún mensaje diciendo que se ha enviado. Lo que yo haría sería cambiar el color de fondo del botón y añadir y tick como diciendo: está enviado.

![descarga 5](https://cloud.githubusercontent.com/assets/20475209/18124754/eabbd342-6f73-11e6-8d30-e9c6a1b12b22.png)

**Comment by mecheverria** [comment]
He retirado el botón de correo, que quizás no tenia mucho sentido en admin (pero se puede volver a poner, y envía el correo solo faltaba publicar una confirmación).

El error de arriba ha sido subsanado.

Cuando no hay comentarios en el momento de la venta, hasta ahora se sustituioa con POS... eso ha sido suprimido.
