### ISSUE TITLE
Mi - Catálogo 

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#24]
En catinfog no tiene ningún sentido esta opción. En redfidelis no lo he probado

![descarga 7](https://cloud.githubusercontent.com/assets/20475209/18125046/0884e49e-6f75-11e6-9b7b-aa2c06dc8665.png)

**Comment by mecheverria** [comment]
El minorista tiene que tener un catalogo en el que controle que productos vende o no, el estock que tiene cada uno el margen comercial que se va a aplicar...
