### ISSUE TITLE
Mi - Error gordo en Informes de devoluciones

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#25]
Me han salido los errores de a imagen cuando he entrado en Informes de devoluciones y he puesto la fecha de inicio que ves en la imagen.

![descarga 8](https://cloud.githubusercontent.com/assets/20475209/18125231/b4e48672-6f75-11e6-9521-addb20ae4d7a.png)

**Comment by mecheverria** [comment]
Resuelto
