### ISSUE TITLE
Mi - error en página principal

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#26]
En el index del panel del minorista aparecen 2 grafios vacíos.
También hay un botón que no lleva a ningún sitio y que está en inglés.
Para acabar, hay un carácter con codificación erronea.

![descarga 10](https://cloud.githubusercontent.com/assets/20475209/18126900/a011209a-6f7d-11e6-928b-d9d67fbafde5.png)

**Comment by mecheverria** [comment]
Resuelto

**Comment by mecheverria** [comment]
Resuelto
