### ISSUE TITLE
Mi - Error al salir de caja

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#27]
He entrado en la caja 1 con el usuario demo y contraseña demo. A continuación le he dado a salir y me ha salido un error. Además, hay 2 botones que me aparecen en inglés cuando deberían salir en español: "Close box" y "Cancel":

![descarga 1](https://cloud.githubusercontent.com/assets/20475209/18136810/4f8c5206-6fa6-11e6-8967-69890fa5e031.png)

![descarga 2](https://cloud.githubusercontent.com/assets/20475209/18136814/547b6da6-6fa6-11e6-8efc-76a87bbd5e0e.png)

Notice: Undefined offset: 4 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined index: in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 958

Notice: Undefined offset: 4 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 5 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 5 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 5 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 5 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 4 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 5 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 5 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 5 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957

Notice: Undefined offset: 5 in /home/admin/web/catinfog.com/public_html/demo/tpv/classes/pos.php on line 957
Usuario: demo

**Comment by mecheverria** [comment]
Resuelto
