### ISSUE TITLE
Mi - Error factura simplificada

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#28]
En la tpv he hecho una venta y cuando tenía que saltar la factura simplificada me ha dado error.

Notice: Undefined index: '0' in /home/admin/web/catinfog.com/public_html/demo/tpv/receipt2.php on line 103

Notice: Undefined index: '0' in /home/admin/web/catinfog.com/public_html/demo/tpv/receipt2.php on line 105

![descarga 4](https://cloud.githubusercontent.com/assets/20475209/18137557/1a986690-6fa9-11e6-9c1e-5a26e4cd6e73.png)

**Comment by mecheverria** [comment]
Resuelto
