### ISSUE TITLE
Mi - Error en opciones

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#29]
Persiste el error en las opciones del panel responsive. Al cambiar por ejemplo el idioma de la tpv y hacer clic en guardar, me salta el siguiente error.

![descarga](https://cloud.githubusercontent.com/assets/20475209/18322480/334c90fa-7533-11e6-99cd-0f99ec5f4e43.png)

**Comment by mecheverria** [comment]
Resuelto
