### ISSUE TITLE
Mi - Error al comprar

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#3]
Salta el siguiente error cuando se hace una compra
![error1](https://cloud.githubusercontent.com/assets/20475209/16909421/f5664bf6-4cd2-11e6-838f-37dc3fd7052f.png)

**Comment by mecheverria** [comment]
Imposible reproducir el error (y la line de codigo en la que ocurre el error tampoco vale porque no se ha registrado la versión del programa (y las lineas cambian de una versión a otra). Probablemente el error está solucionado.
