### ISSUE TITLE
Mi - Error cajas registradoras

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#30]
Las cajas registradoras no funcionan correctamente. Explico paso a paso lo que he hecho:
1-He entrado con el usuario demo en la caja registradora 1. 
2-He vendido varios productos.
3-He hecho clic en salir de caja y me ha salido que el saldo de caja es 0$, cuando es evidente que no es 0$:
![descarga 1](https://cloud.githubusercontent.com/assets/20475209/18322573/a4d469c8-7533-11e6-96d6-957dc8a3c708.png)

4-Al ver este fallo he ido al panel de control responsive del minorista y me he dirigido a la sección "Cajas". Allí todo funciona correctamente. Sin embargo hay fallos que habría que corregir:

- Da las cifras sin moneda.
- Al pinchar en el botón cerrar, cierra la caja sin informar del arqueo.
- Los cierres de caja no los desglosa por método de pago.
- Las filas no las ordena por fecha, sino que las muestra ordenadas por orden alfabético. Lo cual da unos resultados muy poco útiles.
- No señala los miles. Solo los decimales.
- En las devoluciones da este mensaje tan poco útil: product_id: 28. Creo que debería decir que productos se han devuelto y la cantidad.
- En las ventas no indica que productos se han vendido.
- No constan los usos de tickets de descuento.
- No dice a qué cliente se hizo la venta.
- La fecha está a la inglesa. Sería mejor así: Día/Mes/Año
- La columna "Destino" está vacía.

5- Por último, he visto que si se cierra la caja desde el panel de control, no se le cierra la caja al usuario que está en la tpv. Es más, puede seguir haciendo operaciones y no informa de la nueva apertura en el historial.

**Comment by mecheverria** [comment]
Resuelto
