### ISSUE TITLE
Mi - Error en iconos Ventas y compras

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#35]
Hay un error en el uso de los iconos. Creo que crea confusión usar el mismo icono para compras que para ventas.

![descarga 3](https://cloud.githubusercontent.com/assets/20475209/18409945/5e3b8b62-7755-11e6-92da-f2ea76e872dc.png)

Para mejorar esto propongo cambiar el icono de ventas por uno de estos dos. Además, creo que se deberían cambiar el icono que lleva a la tpv por el mismo que el del menú ventas.

`<i class="fa fa-shopping-basket" aria-hidden="true"></i>`
`<i class="fa fa-shopping-bag" aria-hidden="true"></i>`

**Comment by mecheverria** [comment]
Completado
