### ISSUE TITLE
Mi - Errores en Opciones

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#36]
He vuelto a revisar las opciones y veo nuevos errores:
Errores generales:
1- Hay una línea blanca debajo de los botones guardar y cancelar. 
2- Yo quitaría el botón cancelar. No estamos en los 90.
3- Yo no pondría un texto delante de cada método de pago ("Método de pago 1") o caja registradora ("Caja registradora 1"). No es útil. Es mejor poner las id de cada método de pago o caja.

En la pestaña general:
1- Los botones están montados.
2- Cambiar POS por TPV
3- No hay unanimidad con los márgenes.
4- Debería decir "Configuración básica".
5- No somos tillmagic. Mejor que diga: "El Grupo de Clientes por defecto es pos". Aunque hay que estudiar si esto es útil enseñarlo o no.
6- Error de codificación. 
![descarga 4](https://cloud.githubusercontent.com/assets/20475209/18410088/7d04feea-7758-11e6-9439-b2e5e27eeb42.png)

En la pestaña "Métodos de pago" he visto los siguientes errores
1- La primera vez que entras los botones están bien. si embargo, cuando creo un nuevo método de pago, sin guardar hago clic en la pestaña general y vuelvo a la pestaña métodos de pago, los botones se montan. Esto no ocurre si cambio de pestaña sin crear un nuevo método de pago.
2- El color azul para borrar no pega. Si vamos a usar colores, entonces debemos usar colores que nos den información. Para eliminar sería rojo. Si vas a usar rojo, por favor usa el mismo rojo que usa opencart en su panel:
boton {
color: #ffffff;
background-color: #f56b6b;
border-color: #f24545;
}
boton:hover {
color: #ffffff;
background-color: #f23b3b;
border-color: #ea1010;
}
3- Al crear un método de pago, no sigue la serie y empieza a numerar desde 12.
4- El botón para eliminar un método de pago aún sin guardar, es gris.
5- Si vamos a usar un código de colores, quizás el de crear deba ser verde. Te pongo el css que usa opencart en su panel:
boton {
    color: #ffffff;
    background-color: #8fbb6c;
    border-color: #7aae50;
}
boton:hover {
    color: #ffffff;
    background-color: #75a74d;
    border-color: #5c843d;
}
![descarga 5](https://cloud.githubusercontent.com/assets/20475209/18410134/cd51e466-7759-11e6-81a1-27fed4d64b3f.png)

En la pestaña "Cajas registradoras" he visto los siguientes errores.
1- Botones montados. Sin embargo pasa algo extraño. Puesto que al entrar en opciones vas directamente a esta pestaña, los botones están montados. Pero si al entrar en opciones vas primero a "Métodos de pago"  después entras en "Cajas registradoras", los botones no están montados.
2- Botón de borrar en los campos nuevos sin guardar en gris
3- No sigue con el texto de las anteriores cajas.
4- Pone "Crear método de pago" cuando lo que queremos crear es una caja registradora.
![descarga 7](https://cloud.githubusercontent.com/assets/20475209/18410332/737ae0d6-775f-11e6-83af-d92d67409b8f.png)

En la pestaña "Facturas y tickets" yo pondría un breve texto que explique para que sirven los campos a continuación. Además los botones se montan.

En la pestaña "Margen comercial" los botones se montan.

**Comment by mecheverria** [comment]
Completado
