### ISSUE TITLE
Mi - Errores en Cajas

### ISSUE THREAD

**Issue by zaqueoae** [zaqueoae/Catinfog#37]
La sección "Cajas" tiene algunos errores.

1- El título se corresponde con el nombre de la tienda. No pinta nada ahí. Poner algo como "Total de cajas registradoras" o algo así.
2- El ancho de la columna del rol de usuario es desproporcionada y quita espacio a otras columnas.
3- El diseño de la celda id es diferente a la del resto de celdas de la cabecera.
4- El estado de una caja es femenino. Además yo usaría el código de colores. Una bolita al lado verde o roja. 
5- Pensé que era un error, pero no. :+1: 
6- Mal diseño de la celda. No hay espacio. Además el icono debería estar alineado al centro.
7- Mal diseño de la celda. No hay espacio. Además el icono debería estar alineado al centro.
8- El botón cerrar debería seguir los códigos de colores. Si la caja está abierta, el botón en rojo. Si la caja está cerrada, que desaparezca el botón o mejor aún, que esté en verde y nos pida loguearnos en la tpv para esa caja. O mejor aún, que nos loguee con el usuario con el que estamos usando en el panel. Pero vamos, lo más rápido y sencillo. Ya mejoraremos.
Además, cuando se pulsa sobre cerrar, no pasa nada aparentemente. Hay que refrescar la página para ver que se ha cerrado la caja. Además no aparece un sistema de conteo antes de cerrar.

![descarga 10](https://cloud.githubusercontent.com/assets/20475209/18410391/066bebf4-7762-11e6-85b7-433031e88bda.png)

**Comment by mecheverria** [comment]
Completado
